import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

import '../../core/design/snapbee_design.dart';
import '../../models/customer_model.dart';

/// Refer & Earn — shows the customer's real `referral_code` (generated by a
/// DB trigger at sign-up). "Share" copies the code to the clipboard (no
/// share-sheet plugin ships in this app). The referred-friends list uses an
/// honest empty state.
class ReferralsScreen extends StatelessWidget {
  final CustomerModel? customer;

  const ReferralsScreen({super.key, this.customer});

  @override
  Widget build(BuildContext context) {
    final code = customer?.referralCode ?? '—';
    final hasCode = customer?.referralCode != null;

    return Scaffold(
      appBar: const SnapBeeAppBar(
        trailing: Padding(
          padding: EdgeInsets.only(right: 8),
          child: SnapBeePillButton(label: 'How It Works?', icon: Icons.help_outline, color: SnapBeeColors.info),
        ),
      ),
      body: ListView(
        padding: const EdgeInsets.only(bottom: 24),
        children: [
          const SnapBeePageHeader(
            icon: Icons.group_add_rounded,
            title: 'Refer & Earn',
            subtitle: 'Share the good things. Earn rewards together!',
            tint: SnapBeeColors.info,
          ),

          Container(
            margin: const EdgeInsets.fromLTRB(SnapBeeSpacing.gutter, 6, SnapBeeSpacing.gutter, 6),
            padding: const EdgeInsets.all(16),
            decoration: BoxDecoration(color: SnapBeeColors.cream, borderRadius: BorderRadius.circular(SnapBeeSpacing.rCard)),
            child: Row(
              children: [
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text('Good Food Brings People Together!', style: SnapBeeText.h2),
                      const SizedBox(height: 6),
                      Text('Refer your friends to SnapBee and earn rewards.', style: SnapBeeText.body.copyWith(fontSize: 12.5)),
                    ],
                  ),
                ),
                const SnapBeeMascotImage(asset: SnapBeeMascots.refer, height: 78),
              ],
            ),
          ),

          // ---- Referral code card ---------------------------------------
          SnapBeeCard(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text('Your Referral Code', style: SnapBeeText.label),
                const SizedBox(height: 8),
                Row(
                  children: [
                    Expanded(
                      child: Container(
                        padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 12),
                        decoration: BoxDecoration(
                          color: SnapBeeColors.pastelBlue,
                          borderRadius: BorderRadius.circular(SnapBeeSpacing.rTile),
                        ),
                        child: Text(
                          code,
                          style: const TextStyle(fontSize: 18, fontWeight: FontWeight.w800, color: SnapBeeColors.navy, letterSpacing: 1.5),
                        ),
                      ),
                    ),
                    const SizedBox(width: 10),
                    IconButton.filledTonal(
                      onPressed: hasCode
                          ? () {
                              Clipboard.setData(ClipboardData(text: code));
                              ScaffoldMessenger.of(context).showSnackBar(
                                const SnackBar(content: Text('Referral code copied')),
                              );
                            }
                          : null,
                      icon: const Icon(Icons.copy_rounded),
                    ),
                  ],
                ),
                const SizedBox(height: 12),
                SnapBeePrimaryButton(
                  label: 'Share Now',
                  icon: Icons.ios_share_rounded,
                  onPressed: hasCode
                      ? () {
                          Clipboard.setData(ClipboardData(
                            text: 'Join me on SnapBee! Use my referral code $code on your first order. https://snapbee.in',
                          ));
                          ScaffoldMessenger.of(context).showSnackBar(
                            const SnackBar(content: Text('Invite message copied — paste it anywhere to share')),
                          );
                        }
                      : null,
                ),
              ],
            ),
          ),

          // ---- How it works -------------------------------------------
          const SnapBeeSectionHeader(title: 'How It Works?', actionLabel: null),
          const Padding(
            padding: SnapBeeSpacing.screenH,
            child: Column(
              children: [
                _Step(1, Icons.ios_share_rounded, 'Share', 'Share your referral code with your friends.'),
                _Step(2, Icons.person_add_alt_1_rounded, 'Friend Joins', 'Your friend signs up using your code.'),
                _Step(3, Icons.card_giftcard_rounded, 'You Both Earn', 'Get rewards after their first order is completed.'),
              ],
            ),
          ),

          Container(
            margin: SnapBeeSpacing.screenH,
            padding: const EdgeInsets.all(14),
            decoration: BoxDecoration(color: SnapBeeColors.dangerFill, borderRadius: BorderRadius.circular(SnapBeeSpacing.rTile)),
            child: Row(
              children: [
                Expanded(child: _EarnCol('You Earn ₹50', 'When your friend completes their first order')),
                Container(width: 1, height: 34, color: Colors.white),
                const SizedBox(width: 12),
                Expanded(child: _EarnCol('They Get ₹50', 'On their first order')),
              ],
            ),
          ),

          const SnapBeeSectionHeader(title: 'Referred Friends', actionLabel: null),
          Container(
            margin: SnapBeeSpacing.screenH,
            padding: const EdgeInsets.symmetric(vertical: 26, horizontal: 16),
            decoration: BoxDecoration(
              color: SnapBeeColors.surface,
              borderRadius: BorderRadius.circular(SnapBeeSpacing.rTile),
              boxShadow: SnapBeeShadows.soft,
            ),
            child: Column(
              children: [
                Icon(Icons.people_outline_rounded, size: 34, color: SnapBeeColors.inkFaint),
                const SizedBox(height: 10),
                Text('No referrals yet', style: SnapBeeText.title),
                const SizedBox(height: 4),
                Text('Share your code — friends who join will appear here.', textAlign: TextAlign.center, style: SnapBeeText.caption),
              ],
            ),
          ),

          const SnapBeePromoFooter(
            title: 'Together We Grow!',
            subtitle: 'Refer. Earn. Enjoy Better Essentials with SnapBee!',
            scriptAccent: 'More Friends\nMore Rewards!',
          ),
        ],
      ),
    );
  }
}

class _Step extends StatelessWidget {
  final int n;
  final IconData icon;
  final String title;
  final String body;
  const _Step(this.n, this.icon, this.title, this.body);

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 10),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Stack(
            alignment: Alignment.topRight,
            children: [
              Container(
                width: 44,
                height: 44,
                decoration: BoxDecoration(color: SnapBeeColors.orangeTint, shape: BoxShape.circle),
                child: Icon(icon, color: SnapBeeColors.orange, size: 20),
              ),
              Container(
                width: 16,
                height: 16,
                alignment: Alignment.center,
                decoration: const BoxDecoration(color: SnapBeeColors.orange, shape: BoxShape.circle),
                child: Text('$n', style: const TextStyle(color: Colors.white, fontSize: 9, fontWeight: FontWeight.w800)),
              ),
            ],
          ),
          const SizedBox(width: 12),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(title, style: SnapBeeText.title),
                const SizedBox(height: 2),
                Text(body, style: SnapBeeText.caption),
              ],
            ),
          ),
        ],
      ),
    );
  }
}

class _EarnCol extends StatelessWidget {
  final String title;
  final String body;
  const _EarnCol(this.title, this.body);

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(title, style: const TextStyle(fontSize: 13.5, fontWeight: FontWeight.w800, color: SnapBeeColors.danger)),
        const SizedBox(height: 2),
        Text(body, style: SnapBeeText.caption),
      ],
    );
  }
}
